version: "3.8"

services:
  app:
    #image: myapp # if we would like to build an image on the fly use: build: .
    # where the dot after "build:" is the current directory
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/todop

  db:
    image: postgres:14.5-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=todop

